<a href="https://colab.research.google.com/github/Maniganiga404/python-practice/blob/main/Day21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Day21
#numpy
import numpy as np

array1 = np.array([10,20,30])
array2 = np.array([30,50,60])

print(array1 + array2)

[40 70 90]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

arr = np.array([100, 200, 300, 400])

print(arr[2])

300


In [3]:
import numpy as np

np.zeros(2)

array([0., 0.])

In [4]:
import numpy as np

np.ones(2)

array([1., 1.])

In [7]:
import numpy as np
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [12]:
import numpy as np

np.array([[1,2,3],[4,5,6]])

print(arr[0,1])

2


In [13]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2:5])

[30 40 50]


In [17]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr.shape)

print(arr.size)

print(arr.ndim)

print(arr.dtype)

(2, 3)
6
2
int64


In [19]:
import numpy as np

arr = np.array([10,20,30,40,50])

In [20]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr[2, 1])
print(arr[0:2, 1:3])

(3, 3)
9
2
80
[[20 30]
 [50 60]]
