<a href="https://colab.research.google.com/github/Maniganiga404/python-practice/blob/main/Day22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Day22
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr +50)
print(arr + 5)
print(arr - 5)
print(arr * 2)
print(arr / 2)

[60 70 80 90]
[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[ 5. 10. 15. 20.]


In [5]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)

[11 22 33]


In [7]:
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))

100


In [8]:
print(np.mean(arr))

25.0


In [9]:
print(np.min(arr))

print(np.max(arr))

10
40


In [10]:
print(np.std(arr))

11.180339887498949


In [11]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr + 10)

print(arr * 2)

print(arr >50)

print(np.sum(arr))

print(np.mean(arr))

print(np.sum(arr, axis=0))

print(np.sum(arr, axis=1))

[[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]
[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
[[False False False]
 [False False  True]
 [ True  True  True]]
450
50.0
[120 150 180]
[ 60 150 240]
