<a href="https://colab.research.google.com/github/Maniganiga404/python-practice/blob/main/Day23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Day23
#Numpyadvance
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr = np.array([10, 20, 30, 40, 50, 60])

new_arr = arr.reshape(3, 2)

print(new_arr)

[[10 20]
 [30 40]
 [50 60]]


In [4]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

arr.flatten()

array([10, 20, 30, 40, 50, 60])

In [10]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr.T



array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
print(arr.T.shape)

(3, 2)


In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

np.split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [16]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

np.split(arr, [2, 5])

[array([10, 20]), array([30, 40, 50]), array([60, 70])]

In [17]:
np.random.rand(5)

array([0.60768804, 0.97186582, 0.93987689, 0.89808242, 0.48257446])

In [26]:
np.random.randint(1,10,5)

array([4, 1, 2, 5, 3])

In [27]:
np.random.randint(1, 10, (2, 3))

array([[7, 6, 7],
       [9, 4, 2]])

In [51]:
#Practice
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


arr.reshape(3,4)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:


print(arr.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a,b))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

np.split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [43]:
np.split(arr,[3,5])

[array([1, 2, 3]), array([4, 5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [53]:
np.random.randint(1,20,(2,3))

array([[ 6, 11,  7],
       [14, 16, 16]])

In [55]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

arr = arr.reshape(3, 4)

print(arr)

arr.T

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])